# Generated by Django 5.0.6 on 2024-05-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_servicioParqueo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='Tickets',
        ),
    ]
