# Generated by Django 5.0.6 on 2024-05-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_servicioParqueo', '0002_alter_ticket_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='Ticket',
        ),
    ]
